repos:
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        files: '^(src)/'

  - repo: https://github.com/pycqa/pylint
    rev: 'v3.0.0'
    hooks:
      - id: pylint
        files: '^(src)/'
